---
title: "Object Orientation in Ruby"
type: "article"
description: "Overview of how object-oriented programming is implemented in Ruby, with
a comparison to objects in JavaScript."
tags: "oop, object-composition"
